#ifndef LWB_CUSTOM_CONF_H_
#define LWB_CUSTOM_CONF_H_

#define LWB_CONF_T_GAP      (RTIMER_SECOND / 250) // 4 ms
#define LWB_CONF_T_RR_ON    (RTIMER_SECOND / 30) // 33 ms

#define LWB_CONF_T_GUARD    (RTIMER_SECOND / 1000) // 1 ms

#define LWB_CONF_MAX_DATA_BUF_ELEMENTS 8

#endif // LWB_CUSTOM_CONF_H_
